using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;

namespace RecycleScroll.Editor
{
    /// <summary>
    /// MenuItem 이름은 컴파일 타임 상수라 런타임에 만들 수 없고,
    /// 런타임 등록 API인 UnityEditor.Menu.AddMenuItem 은 internal 이다.
    /// 그래서 템플릿 메뉴는 Assets 아래에 .cs 파일로 생성해 컴파일시킨다.
    /// </summary>
    internal static class RecycleScrollerTemplateMenuGenerator
    {
        private const string GENERATED_ROOT = "Assets/RecycleScroller.Generated";
        private const string GENERATED_DIR = GENERATED_ROOT + "/Editor";
        private const string GENERATED_FILE = GENERATED_DIR + "/RecycleScrollerTemplateMenu.cs";

        // 기존 메뉴는 priority 미지정(기본 1000)이다. 11 이상 벌려야 Unity가 구분선을 넣는다.
        private const int MENU_PRIORITY_BASE = 1011;

        public static void Generate(IReadOnlyList<TemplateEntry> templates)
        {
            var code = BuildCode(templates);
            if (code is null)
            {
                DeleteGenerated();
                return;
            }

            if (File.Exists(GENERATED_FILE) && File.ReadAllText(GENERATED_FILE) == code) return;

            Directory.CreateDirectory(GENERATED_DIR);
            File.WriteAllText(GENERATED_FILE, code);
            AssetDatabase.ImportAsset(GENERATED_FILE, ImportAssetOptions.ForceUpdate);
        }

        /// <summary>생성할 소스 코드 전문. 유효한 템플릿이 하나도 없으면 null.</summary>
        internal static string BuildCode(IReadOnlyList<TemplateEntry> templates)
        {
            var body = new StringBuilder();
            var emitted = 0;

            for (int i = 0; i < templates.Count; i++)
            {
                var entry = templates[i];
                if (entry is null || entry.m_prefab == null) continue;

                var menuName = EscapeForLiteral(RecycleScrollerTemplateSettings.GetDisplayName(entry, i));
                if (string.IsNullOrWhiteSpace(menuName)) continue;

                var priority = MENU_PRIORITY_BASE + emitted;
                body.AppendLine($"    [UnityEditor.MenuItem(\"{RecycleScrollViewCreator.MENU_PATH}{menuName}\", false, {priority})]");
                body.AppendLine($"    private static void CreateTemplate{i}(UnityEditor.MenuCommand command)");
                body.AppendLine($"        => RecycleScrollViewCreator.CreateFromTemplate(command, {i});");
                body.AppendLine();

                emitted++;
            }

            if (emitted == 0) return null;

            return "// <auto-generated>\n"
                 + "//     RecycleScroller 템플릿 설정에서 생성된 파일입니다. 직접 수정하지 마세요.\n"
                 + $"//     {RecycleScrollerTemplateSettings.SETTINGS_MENU_PATH} 에서 편집하세요.\n"
                 + "// </auto-generated>\n"
                 + "internal static class RecycleScrollerTemplateMenu\n"
                 + "{\n"
                 + body.ToString().TrimEnd() + "\n"
                 + "}\n";
        }

        /// <summary>
        /// 생성 코드 안에서 문자열 리터럴로 들어가므로 역슬래시와 따옴표는 제거한다.
        /// 남겨두면 생성된 .cs 가 컴파일되지 않는다. '/' 는 서브메뉴 표기라 그대로 둔다.
        /// </summary>
        internal static string EscapeForLiteral(string menuName)
            => menuName.Replace("\\", string.Empty).Replace("\"", string.Empty).Trim();

        private static void DeleteGenerated()
        {
            if (File.Exists(GENERATED_FILE) is false) return;

            AssetDatabase.DeleteAsset(GENERATED_FILE);
            DeleteFolderIfEmpty(GENERATED_DIR);
            DeleteFolderIfEmpty(GENERATED_ROOT);
        }

        private static void DeleteFolderIfEmpty(string folder)
        {
            if (Directory.Exists(folder) is false) return;
            if (Directory.GetFileSystemEntries(folder).Length > 0) return;

            AssetDatabase.DeleteAsset(folder);
        }
    }
}
